### ISSUE TITLE
Always returns zero results

### ISSUE THREAD

**Issue by ossigeno** [gustavotr/upwork-scraper#3]
Status = Succeeded
Results = 0 items

`2020-11-18T08:56:47.477Z ACTOR: Creating Docker container.
2020-11-18T08:56:47.799Z ACTOR: Starting Docker container.
2020-11-18T08:56:49.670Z INFO  System info {"apifyVersion":"0.21.3","apifyClientVersion":"0.6.0","osType":"Linux","nodeVersion":"v12.18.2"}
2020-11-18T08:56:49.758Z DEBUG RequestList: Loaded state from key value store using the persistStateKey.
2020-11-18T08:56:50.233Z INFO  Starting the crawl.
2020-11-18T08:56:50.343Z DEBUG PuppeteerCrawler:AutoscaledPool: scaling up {"oldConcurrency":1,"newConcurrency":2,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":null},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":null},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":null},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":null}}}
2020-11-18T08:56:50.345Z INFO  PuppeteerCrawler:AutoscaledPool: state {"currentConcurrency":0,"desiredConcurrency":2,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":null},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":null},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":null},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":null}}}
2020-11-18T08:56:51.913Z DEBUG PuppeteerCrawler:PuppeteerPool: Launching new browser {"id":0}
2020-11-18T08:56:51.915Z DEBUG PuppeteerCrawler:SessionPool: Created new Session - session_fDLdYBylsi
2020-11-18T08:56:52.002Z INFO  Launching Puppeteer {"stealth":true,"devtools":false,"args":["--no-sandbox","--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36"],"timeout":15000,"headless":true,"defaultViewport":{"width":1366,"height":768},"proxyUrl":"http://groups-SHADER,session-session_fDLdYBylsi:<redacted>@10.0.34.8:8011/"}
2020-11-18T08:57:00.346Z DEBUG PuppeteerCrawler:AutoscaledPool: scaling up {"oldConcurrency":2,"newConcurrency":3,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":0},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":0},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":0},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":0}}}
2020-11-18T08:57:08.551Z DEBUG PuppeteerCrawler:PuppeteerPool: Retiring browser {"id":0}
2020-11-18T08:57:46.268Z INFO  Processing https://www.upwork.com/search/profiles/...
2020-11-18T08:57:46.273Z DEBUG Profile search url...
2020-11-18T08:57:49.676Z DEBUG PuppeteerCrawler:SessionPool: Persisting state {"persistStateKeyValueStoreId":null,"persistStateKey":"SESSION_POOL_STATE"}
2020-11-18T08:57:50.332Z DEBUG PuppeteerCrawler:PuppeteerPool: Retired browsers count {"count":1}
2020-11-18T08:57:50.344Z INFO  PuppeteerCrawler request statistics: {"avgDurationMillis":null,"perMinute":0,"finished":0,"failed":0,"retryHistogram":[]}
2020-11-18T08:57:50.352Z INFO  PuppeteerCrawler:AutoscaledPool: state {"currentConcurrency":1,"desiredConcurrency":3,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":0},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":0},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":0.096},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":0}}}
2020-11-18T08:58:16.275Z DEBUG Normal search
2020-11-18T08:58:46.278Z ERROR PuppeteerCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.upwork.com/search/profiles/","retryCount":1,"id":"eGCyYnl7VHrggqp"}
2020-11-18T08:58:46.281Z   Error: handlePageFunction timed out after 60 seconds.
2020-11-18T08:58:46.295Z       at Timeout.<anonymous> (/home/myuser/node_modules/apify/build/utils.js:360:49)
2020-11-18T08:58:46.297Z       at listOnTimeout (internal/timers.js:549:17)
2020-11-18T08:58:46.299Z       at processTimers (internal/timers.js:492:7)
2020-11-18T08:58:47.294Z DEBUG PuppeteerCrawler:PuppeteerPool: Killing retired browser because it has no active pages {"id":0}
2020-11-18T08:58:47.298Z DEBUG PuppeteerCrawler:PuppeteerPool: Killing browser {"id":0}
2020-11-18T08:58:47.375Z DEBUG PuppeteerCrawler:PuppeteerPool: browser is retired already {"id":0}
2020-11-18T08:58:49.612Z DEBUG PuppeteerCrawler:PuppeteerPool: Launching new browser {"id":1}
2020-11-18T08:58:49.615Z DEBUG PuppeteerCrawler:SessionPool: Created new Session - session_Iml2c8s7jD
2020-11-18T08:58:49.645Z INFO  Launching Puppeteer {"stealth":true,"devtools":false,"args":["--no-sandbox","--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36"],"timeout":15000,"headless":true,"defaultViewport":{"width":1366,"height":768},"proxyUrl":"http://groups-SHADER,session-session_Iml2c8s7jD:<redacted>@10.0.34.8:8011/"}
2020-11-18T08:58:49.688Z DEBUG PuppeteerCrawler:SessionPool: Persisting state {"persistStateKeyValueStoreId":null,"persistStateKey":"SESSION_POOL_STATE"}
2020-11-18T08:58:50.464Z DEBUG PuppeteerCrawler:PuppeteerPool: Retired browsers count {"count":0}
2020-11-18T08:58:50.466Z INFO  PuppeteerCrawler request statistics: {"avgDurationMillis":null,"perMinute":0,"finished":0,"failed":0,"retryHistogram":[]}
2020-11-18T08:58:50.553Z 
2020-11-18T08:58:50.646Z INFO  PuppeteerCrawler:AutoscaledPool: state {"currentConcurrency":1,"desiredConcurrency":3,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":0},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":0},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":0.048},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":0}}}
2020-11-18T08:59:08.296Z DEBUG PuppeteerCrawler:PuppeteerPool: Retiring browser {"id":1}
2020-11-18T08:59:18.148Z INFO  Processing https://www.upwork.com/search/profiles/...
2020-11-18T08:59:18.388Z DEBUG Profile search url...
2020-11-18T08:59:48.445Z DEBUG Normal search
2020-11-18T08:59:49.689Z DEBUG PuppeteerCrawler:SessionPool: Persisting state {"persistStateKeyValueStoreId":null,"persistStateKey":"SESSION_POOL_STATE"}
2020-11-18T08:59:50.463Z DEBUG PuppeteerCrawler:PuppeteerPool: Retired browsers count {"count":1}
2020-11-18T08:59:50.466Z INFO  PuppeteerCrawler request statistics: {"avgDurationMillis":null,"perMinute":0,"finished":0,"failed":0,"retryHistogram":[]}
2020-11-18T08:59:50.656Z INFO  PuppeteerCrawler:AutoscaledPool: state {"currentConcurrency":1,"desiredConcurrency":3,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":0},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":0},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":0.131},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":0}}}
2020-11-18T09:00:18.171Z ERROR PuppeteerCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.upwork.com/search/profiles/","retryCount":2,"id":"eGCyYnl7VHrggqp"}
2020-11-18T09:00:18.173Z   Error: handlePageFunction timed out after 60 seconds.
2020-11-18T09:00:18.176Z       at Timeout.<anonymous> (/home/myuser/node_modules/apify/build/utils.js:360:49)
2020-11-18T09:00:18.178Z       at listOnTimeout (internal/timers.js:549:17)
2020-11-18T09:00:18.180Z       at processTimers (internal/timers.js:492:7)
2020-11-18T09:00:19.168Z DEBUG PuppeteerCrawler:PuppeteerPool: Killing retired browser because it has no active pages {"id":1}
2020-11-18T09:00:19.171Z DEBUG PuppeteerCrawler:PuppeteerPool: Killing browser {"id":1}
2020-11-18T09:00:19.344Z DEBUG PuppeteerCrawler:PuppeteerPool: browser is retired already {"id":1}
2020-11-18T09:00:21.590Z DEBUG PuppeteerCrawler:PuppeteerPool: Launching new browser {"id":2}
2020-11-18T09:00:21.592Z DEBUG PuppeteerCrawler:SessionPool: Created new Session - session_qj8RirK9bD
2020-11-18T09:00:21.616Z INFO  Launching Puppeteer {"stealth":true,"devtools":false,"args":["--no-sandbox","--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36"],"timeout":15000,"headless":true,"defaultViewport":{"width":1366,"height":768},"proxyUrl":"http://groups-SHADER,session-session_qj8RirK9bD:<redacted>@10.0.34.8:8011/"}
2020-11-18T09:00:38.852Z INFO  Processing https://www.upwork.com/search/profiles/...
2020-11-18T09:00:39.362Z DEBUG Profile search url...
2020-11-18T09:00:49.689Z DEBUG PuppeteerCrawler:SessionPool: Persisting state {"persistStateKeyValueStoreId":null,"persistStateKey":"SESSION_POOL_STATE"}
2020-11-18T09:00:50.463Z DEBUG PuppeteerCrawler:PuppeteerPool: Retired browsers count {"count":0}
2020-11-18T09:00:50.474Z INFO  PuppeteerCrawler request statistics: {"avgDurationMillis":null,"perMinute":0,"finished":0,"failed":0,"retryHistogram":[]}
2020-11-18T09:00:50.749Z INFO  PuppeteerCrawler:AutoscaledPool: state {"currentConcurrency":1,"desiredConcurrency":3,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":0},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":0.059},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":0.185},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":0}}}
2020-11-18T09:01:09.364Z DEBUG Normal search
2020-11-18T09:01:38.868Z ERROR PuppeteerCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.upwork.com/search/profiles/","retryCount":3,"id":"eGCyYnl7VHrggqp"}
2020-11-18T09:01:38.871Z   Error: handlePageFunction timed out after 60 seconds.
2020-11-18T09:01:38.873Z       at Timeout.<anonymous> (/home/myuser/node_modules/apify/build/utils.js:360:49)
2020-11-18T09:01:38.875Z       at listOnTimeout (internal/timers.js:549:17)
2020-11-18T09:01:38.878Z       at processTimers (internal/timers.js:492:7)
2020-11-18T09:01:49.664Z INFO  Processing https://www.upwork.com/search/profiles/...
2020-11-18T09:01:49.744Z DEBUG PuppeteerCrawler:SessionPool: Persisting state {"persistStateKeyValueStoreId":null,"persistStateKey":"SESSION_POOL_STATE"}
2020-11-18T09:01:50.164Z DEBUG Profile search url...
2020-11-18T09:01:50.463Z DEBUG PuppeteerCrawler:PuppeteerPool: Retired browsers count {"count":0}
2020-11-18T09:01:50.473Z INFO  PuppeteerCrawler request statistics: {"avgDurationMillis":null,"perMinute":0,"finished":0,"failed":0,"retryHistogram":[]}
2020-11-18T09:01:50.761Z INFO  PuppeteerCrawler:AutoscaledPool: state {"currentConcurrency":1,"desiredConcurrency":3,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":0},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":0},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":0.167},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":0}}}
2020-11-18T09:02:20.166Z DEBUG Normal search
2020-11-18T09:02:49.707Z ERROR Request failed too many times: https://www.upwork.com/search/profiles/
2020-11-18T09:02:49.750Z DEBUG PuppeteerCrawler:SessionPool: Persisting state {"persistStateKeyValueStoreId":null,"persistStateKey":"SESSION_POOL_STATE"}
2020-11-18T09:02:49.789Z INFO  PuppeteerCrawler: All the requests from request list and/or request queue have been processed, the crawler will shut down.
2020-11-18T09:02:49.792Z INFO  PuppeteerCrawler: Final request statistics: {"avgDurationMillis":null,"perMinute":0,"finished":0,"failed":1,"retryHistogram":[null,null,null,1]}
2020-11-18T09:02:49.794Z DEBUG PuppeteerCrawler:SessionPool: Persisting state {"persistStateKeyValueStoreId":null,"persistStateKey":"SESSION_POOL_STATE"}
2020-11-18T09:02:49.987Z DEBUG PuppeteerCrawler:PuppeteerPool: Retiring browser {"id":2}
2020-11-18T09:02:50.050Z INFO  Crawl finished.`

**Comment by gustavotr** [comment]
Upwork updated its page and made the old version obsolete. I updated the scraper partially so now it should work now.
